allowBuilds:
  '@google/genai': false
  '@parcel/watcher': true
  better-sqlite3: true
  electron: true
  esbuild: true
  keytar: true
  protobufjs: false
  sharp: true
  uiohook-napi: true

blockExoticSubdeps: false
