DROP TABLE `ai_usage_event_outbox`;--> statement-breakpoint
DROP TABLE `ai_usage_events`;--> statement-breakpoint
DROP TABLE `automation_rules`;--> statement-breakpoint
DROP TABLE `conversation_route_events`;--> statement-breakpoint
DROP TABLE `conversation_route_snapshots`;--> statement-breakpoint
DROP TABLE `documents`;--> statement-breakpoint
DROP TABLE `folders`;--> statement-breakpoint
DROP TABLE `linked_folder_mounts`;--> statement-breakpoint
DROP TABLE `memory_edges`;--> statement-breakpoint
DROP TABLE `memory_keywords`;--> statement-breakpoint
DROP TABLE `memory_note_keywords`;--> statement-breakpoint
DROP TABLE `memory_notes`;--> statement-breakpoint
DROP TABLE `memory_sections`;--> statement-breakpoint
DROP TABLE `memory_sync_jobs`;--> statement-breakpoint
DROP TABLE `memory_topics`;--> statement-breakpoint
DROP TABLE `project_audit_logs`;--> statement-breakpoint
DROP TABLE `project_candidates`;--> statement-breakpoint
DROP TABLE `project_events`;--> statement-breakpoint
DROP TABLE `project_links`;--> statement-breakpoint
DROP TABLE `project_milestones`;--> statement-breakpoint
DROP TABLE `project_reminder_links`;--> statement-breakpoint
DROP TABLE `project_snapshots`;--> statement-breakpoint
DROP TABLE `recycle_bin`;--> statement-breakpoint
DROP TABLE `resource_tags`;--> statement-breakpoint
DROP TABLE `resources`;--> statement-breakpoint
DROP TABLE `rss_feed_items`;--> statement-breakpoint
DROP TABLE `tracked_projects`;--> statement-breakpoint
DROP TABLE `workflow_runs`;--> statement-breakpoint
DROP TABLE `workflows`;