export enum AppEvent {
  // Sprite
  SPRITE_AI_START = 'SPRITE_AI_START',
  SPRITE_AI_COMPLETED = 'SPRITE_AI_COMPLETED',
  SPRITE_AI_ERROR = 'SPRITE_AI_ERROR',
  AI_PROVIDER_CONFIG_UPDATED = 'AI_PROVIDER_CONFIG_UPDATED',

  // Sprite — Download
  SPRITE_DOWNLOAD_START = 'SPRITE_DOWNLOAD_START',
  SPRITE_DOWNLOAD_PROGRESS = 'SPRITE_DOWNLOAD_PROGRESS',
  SPRITE_DOWNLOAD_COMPLETE = 'SPRITE_DOWNLOAD_COMPLETE',
  SPRITE_DOWNLOAD_FAILED = 'SPRITE_DOWNLOAD_FAILED',

  // Sprite — Plugin
  SPRITE_PLUGIN_INSTALLED = 'SPRITE_PLUGIN_INSTALLED',
  SPRITE_PLUGIN_REMOVED = 'SPRITE_PLUGIN_REMOVED',

  // Sprite — System Lifecycle
  SPRITE_SYSTEM_READY = 'SPRITE_SYSTEM_READY',
  SPRITE_SYSTEM_QUIT = 'SPRITE_SYSTEM_QUIT',

  // System
  APP_WINDOW_OPENED = 'APP_WINDOW_OPENED',
  APP_WINDOW_CLOSED = 'APP_WINDOW_CLOSED',

  // AI Agent Loop
  AGENT_LOOP_COMPLETE = 'AGENT_LOOP_COMPLETE'
}
