export enum AppEvent {
  // Workspace
  WORKSPACE_CREATED = 'WORKSPACE_CREATED',
  WORKSPACE_UPDATED = 'WORKSPACE_UPDATED',
  WORKSPACE_DELETED = 'WORKSPACE_DELETED',
  WORKSPACE_WIZARD_CLOSED = 'WORKSPACE_WIZARD_CLOSED',

  // Folder
  FOLDER_CREATED = 'FOLDER_CREATED',
  FOLDER_UPDATED = 'FOLDER_UPDATED',
  FOLDER_DELETED = 'FOLDER_DELETED',
  FOLDER_MOVED = 'FOLDER_MOVED',
  LINKED_DIRECTORY_SYNCED = 'LINKED_DIRECTORY_SYNCED',

  // Resource
  RESOURCE_CREATED = 'RESOURCE_CREATED',
  RESOURCE_UPDATED = 'RESOURCE_UPDATED',
  RESOURCE_DELETED = 'RESOURCE_DELETED',
  RESOURCE_MOVED = 'RESOURCE_MOVED',
  RESOURCE_BATCH_DELETED = 'RESOURCE_BATCH_DELETED',
  RESOURCE_BATCH_MOVED = 'RESOURCE_BATCH_MOVED',

  // Tag
  TAG_CREATED = 'TAG_CREATED',
  TAG_UPDATED = 'TAG_UPDATED',
  TAG_DELETED = 'TAG_DELETED',

  // Sprite
  SPRITE_MESSAGE = 'SPRITE_MESSAGE',
  SPRITE_AI_START = 'SPRITE_AI_START',
  SPRITE_AI_COMPLETE = 'SPRITE_AI_COMPLETE',
  SPRITE_AI_ERROR = 'SPRITE_AI_ERROR',
  SPRITE_WORKFLOW_START = 'SPRITE_WORKFLOW_START',
  SPRITE_WORKFLOW_PROGRESS = 'SPRITE_WORKFLOW_PROGRESS',
  SPRITE_WORKFLOW_COMPLETE = 'SPRITE_WORKFLOW_COMPLETE',
  SPRITE_WORKFLOW_FAIL = 'SPRITE_WORKFLOW_FAIL',
  SPRITE_WORKFLOW_CANCEL = 'SPRITE_WORKFLOW_CANCEL',
  SPRITE_RESOURCE_IMPORT_START = 'SPRITE_RESOURCE_IMPORT_START',
  SPRITE_RESOURCE_IMPORT_PROGRESS = 'SPRITE_RESOURCE_IMPORT_PROGRESS',
  SPRITE_RESOURCE_IMPORT_COMPLETE = 'SPRITE_RESOURCE_IMPORT_COMPLETE',
  SPRITE_RESOURCE_IMPORT_ERROR = 'SPRITE_RESOURCE_IMPORT_ERROR',

  // Sprite — Download
  SPRITE_DOWNLOAD_START = 'SPRITE_DOWNLOAD_START',
  SPRITE_DOWNLOAD_PROGRESS = 'SPRITE_DOWNLOAD_PROGRESS',
  SPRITE_DOWNLOAD_COMPLETE = 'SPRITE_DOWNLOAD_COMPLETE',
  SPRITE_DOWNLOAD_FAIL = 'SPRITE_DOWNLOAD_FAIL',

  // Sprite — Plugin
  SPRITE_PLUGIN_INSTALL = 'SPRITE_PLUGIN_INSTALL',
  SPRITE_PLUGIN_REMOVE = 'SPRITE_PLUGIN_REMOVE',
  SPRITE_PLUGIN_UPDATE = 'SPRITE_PLUGIN_UPDATE',

  // Sprite — System Lifecycle
  SPRITE_SYSTEM_READY = 'SPRITE_SYSTEM_READY',
  SPRITE_SYSTEM_QUIT = 'SPRITE_SYSTEM_QUIT',
  SPRITE_SYSTEM_FOCUS = 'SPRITE_SYSTEM_FOCUS',
  SPRITE_SYSTEM_BLUR = 'SPRITE_SYSTEM_BLUR',

  // Sprite — Network
  SPRITE_NETWORK_CONNECT = 'SPRITE_NETWORK_CONNECT',
  SPRITE_NETWORK_DISCONNECT = 'SPRITE_NETWORK_DISCONNECT',
  SPRITE_NETWORK_TIMEOUT = 'SPRITE_NETWORK_TIMEOUT',

  // Sprite — Media Processing
  SPRITE_MEDIA_PROCESS_START = 'SPRITE_MEDIA_PROCESS_START',
  SPRITE_MEDIA_PROCESS_COMPLETE = 'SPRITE_MEDIA_PROCESS_COMPLETE',

  // Sprite — RSS
  SPRITE_RSS_REFRESH = 'SPRITE_RSS_REFRESH',
  SPRITE_RSS_NEW_CONTENT = 'SPRITE_RSS_NEW_CONTENT',

  // Sprite — Trash
  SPRITE_TRASH_DELETE = 'SPRITE_TRASH_DELETE',
  SPRITE_TRASH_RESTORE = 'SPRITE_TRASH_RESTORE',

  // Spleeter
  SPLEETER_PROGRESS = 'SPLEETER_PROGRESS',

  // System
  APP_STARTED = 'APP_STARTED',

  // AI Agent Loop
  AGENT_LOOP_COMPLETE = 'AGENT_LOOP_COMPLETE',

  // Memory
  MEMORY_EXTRACTION_STARTED = 'MEMORY_EXTRACTION_STARTED',
  MEMORY_EXTRACTION_PROGRESS = 'MEMORY_EXTRACTION_PROGRESS',
  MEMORY_EXTRACTION_COMPLETED = 'MEMORY_EXTRACTION_COMPLETED',
  MEMORY_EXTRACTION_FAILED = 'MEMORY_EXTRACTION_FAILED',

  // User Persona Profile
  USER_PERSONA_UPDATE_STARTED = 'USER_PERSONA_UPDATE_STARTED',
  USER_PERSONA_UPDATE_COMPLETED = 'USER_PERSONA_UPDATE_COMPLETED',
  USER_PERSONA_UPDATE_FAILED = 'USER_PERSONA_UPDATE_FAILED',
  USER_PERSONA_UPDATE_SKIPPED = 'USER_PERSONA_UPDATE_SKIPPED'
}

export interface AppEventPayload<T = any> {
  type: AppEvent;
  data?: T;
  timestamp: number;
  sourceWindowId?: number; // ID of the window that initiated the change
}

export const APP_EVENT_CHANNEL = 'APP_EVENT_CHANNEL';
