export enum AppEvent {
  // Workspace
  WORKSPACE_CREATED = 'WORKSPACE_CREATED',
  WORKSPACE_UPDATED = 'WORKSPACE_UPDATED',
  WORKSPACE_DELETED = 'WORKSPACE_DELETED',
  WORKSPACE_WIZARD_CLOSED = 'WORKSPACE_WIZARD_CLOSED',

  // Folder
  FOLDER_CREATED = 'FOLDER_CREATED',
  FOLDER_UPDATED = 'FOLDER_UPDATED',
  FOLDER_DELETED = 'FOLDER_DELETED',
  FOLDER_MOVED = 'FOLDER_MOVED',
  LINKED_DIRECTORY_SYNCED = 'LINKED_DIRECTORY_SYNCED',

  // Tag
  TAG_CREATED = 'TAG_CREATED',
  TAG_UPDATED = 'TAG_UPDATED',
  TAG_DELETED = 'TAG_DELETED',

  // Sprite
  SPRITE_MESSAGE = 'SPRITE_MESSAGE',
  SPRITE_AI_START = 'SPRITE_AI_START',
  SPRITE_AI_COMPLETED = 'SPRITE_AI_COMPLETED',
  SPRITE_AI_ERROR = 'SPRITE_AI_ERROR',
  AI_PROVIDER_CONFIG_UPDATED = 'AI_PROVIDER_CONFIG_UPDATED',
  SPRITE_MENU_ITEM_SELECTED = 'SPRITE_MENU_ITEM_SELECTED',
  FILE_ACTION_SELECTED = 'FILE_ACTION_SELECTED',
  FILE_ACTION_WORKFLOW_STARTED = 'FILE_ACTION_WORKFLOW_STARTED',
  FILE_ACTION_OCR_COMPLETED = 'FILE_ACTION_OCR_COMPLETED',
  FILE_ACTION_RESOLVED = 'FILE_ACTION_RESOLVED',
  FILE_ACTION_FAILED = 'FILE_ACTION_FAILED',
  FILE_ACTION_CANCELLED = 'FILE_ACTION_CANCELLED',

  // Sprite — Download
  SPRITE_DOWNLOAD_START = 'SPRITE_DOWNLOAD_START',
  SPRITE_DOWNLOAD_PROGRESS = 'SPRITE_DOWNLOAD_PROGRESS',
  SPRITE_DOWNLOAD_COMPLETE = 'SPRITE_DOWNLOAD_COMPLETE',
  SPRITE_DOWNLOAD_FAILED = 'SPRITE_DOWNLOAD_FAILED',

  // Sprite — Plugin
  SPRITE_PLUGIN_INSTALLED = 'SPRITE_PLUGIN_INSTALLED',
  SPRITE_PLUGIN_REMOVED = 'SPRITE_PLUGIN_REMOVED',
  SPRITE_PLUGIN_UPDATE = 'SPRITE_PLUGIN_UPDATE',

  // Sprite — System Lifecycle
  SPRITE_SYSTEM_READY = 'SPRITE_SYSTEM_READY',
  SPRITE_SYSTEM_QUIT = 'SPRITE_SYSTEM_QUIT',
  SPRITE_SYSTEM_FOCUS = 'SPRITE_SYSTEM_FOCUS',
  SPRITE_SYSTEM_BLUR = 'SPRITE_SYSTEM_BLUR',

  // Sprite — Network
  SPRITE_NETWORK_CONNECT = 'SPRITE_NETWORK_CONNECT',
  SPRITE_NETWORK_DISCONNECT = 'SPRITE_NETWORK_DISCONNECT',
  SPRITE_NETWORK_TIMEOUT = 'SPRITE_NETWORK_TIMEOUT',

  // System
  APP_STARTED = 'APP_STARTED',
  APP_WINDOW_OPENED = 'APP_WINDOW_OPENED',
  APP_WINDOW_CLOSED = 'APP_WINDOW_CLOSED',

  // AI Agent Loop
  AGENT_LOOP_COMPLETE = 'AGENT_LOOP_COMPLETE',

  // Project Tracking
  PROJECT_CANDIDATE_CREATED = 'PROJECT_CANDIDATE_CREATED'
}

export interface AppEventPayload<T = any> {
  type: AppEvent;
  data?: T;
  timestamp: number;
  sourceWindowId?: number; // ID of the window that initiated the change
}

export const APP_EVENT_CHANNEL = 'APP_EVENT_CHANNEL';
