// MiniMax official system voice list.
// Source: https://platform.minimaxi.com/docs/faq/system-voice-id
// Synced: 2026-07-01

export interface MiniMaxSystemVoice {
  value: string;
  label: string;
  lang: string;
}

export interface MiniMaxSystemVoiceGroup {
  lang: string;
  voices: MiniMaxSystemVoice[];
}

export const MINIMAX_SYSTEM_VOICES = [
  { value: 'male-qn-qingse', label: '青涩青年音色', lang: '中文 (普通话)' },
  { value: 'male-qn-jingying', label: '精英青年音色', lang: '中文 (普通话)' },
  { value: 'male-qn-badao', label: '霸道青年音色', lang: '中文 (普通话)' },
  { value: 'male-qn-daxuesheng', label: '青年大学生音色', lang: '中文 (普通话)' },
  { value: 'female-shaonv', label: '少女音色', lang: '中文 (普通话)' },
  { value: 'female-yujie', label: '御姐音色', lang: '中文 (普通话)' },
  { value: 'female-chengshu', label: '成熟女性音色', lang: '中文 (普通话)' },
  { value: 'female-tianmei', label: '甜美女性音色', lang: '中文 (普通话)' },
  { value: 'male-qn-qingse-jingpin', label: '青涩青年音色-beta', lang: '中文 (普通话)' },
  { value: 'male-qn-jingying-jingpin', label: '精英青年音色-beta', lang: '中文 (普通话)' },
  { value: 'male-qn-badao-jingpin', label: '霸道青年音色-beta', lang: '中文 (普通话)' },
  { value: 'male-qn-daxuesheng-jingpin', label: '青年大学生音色-beta', lang: '中文 (普通话)' },
  { value: 'female-shaonv-jingpin', label: '少女音色-beta', lang: '中文 (普通话)' },
  { value: 'female-yujie-jingpin', label: '御姐音色-beta', lang: '中文 (普通话)' },
  { value: 'female-chengshu-jingpin', label: '成熟女性音色-beta', lang: '中文 (普通话)' },
  { value: 'female-tianmei-jingpin', label: '甜美女性音色-beta', lang: '中文 (普通话)' },
  { value: 'clever_boy', label: '聪明男童', lang: '中文 (普通话)' },
  { value: 'cute_boy', label: '可爱男童', lang: '中文 (普通话)' },
  { value: 'lovely_girl', label: '萌萌女童', lang: '中文 (普通话)' },
  { value: 'cartoon_pig', label: '卡通猪小琪', lang: '中文 (普通话)' },
  { value: 'bingjiao_didi', label: '病娇弟弟', lang: '中文 (普通话)' },
  { value: 'junlang_nanyou', label: '俊朗男友', lang: '中文 (普通话)' },
  { value: 'chunzhen_xuedi', label: '纯真学弟', lang: '中文 (普通话)' },
  { value: 'lengdan_xiongzhang', label: '冷淡学长', lang: '中文 (普通话)' },
  { value: 'badao_shaoye', label: '霸道少爷', lang: '中文 (普通话)' },
  { value: 'tianxin_xiaoling', label: '甜心小玲', lang: '中文 (普通话)' },
  { value: 'qiaopi_mengmei', label: '俏皮萌妹', lang: '中文 (普通话)' },
  { value: 'wumei_yujie', label: '妩媚御姐', lang: '中文 (普通话)' },
  { value: 'diadia_xuemei', label: '嗲嗲学妹', lang: '中文 (普通话)' },
  { value: 'danya_xuejie', label: '淡雅学姐', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Reliable_Executive', label: '沉稳高管', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_News_Anchor', label: '新闻女声', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Mature_Woman', label: '傲娇御姐', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Unrestrained_Young_Man', label: '不羁青年', lang: '中文 (普通话)' },
  { value: 'Arrogant_Miss', label: '嚣张小姐', lang: '中文 (普通话)' },
  { value: 'Robot_Armor', label: '机械战甲', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Kind-hearted_Antie', label: '热心大婶', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_HK_Flight_Attendant', label: '港普空姐', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Humorous_Elder', label: '搞笑大爷', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Gentleman', label: '温润男声', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Warm_Bestie', label: '温暖闺蜜', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Male_Announcer', label: '播报男声', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Sweet_Lady', label: '甜美女声', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Southern_Young_Man', label: '南方小哥', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Wise_Women', label: '阅历姐姐', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Gentle_Youth', label: '温润青年', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Warm_Girl', label: '温暖少女', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Kind-hearted_Elder', label: '花甲奶奶', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Cute_Spirit', label: '憨憨萌兽', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Radio_Host', label: '电台男主播', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Lyrical_Voice', label: '抒情男声', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Straightforward_Boy', label: '率真弟弟', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Sincere_Adult', label: '真诚青年', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Gentle_Senior', label: '温柔学姐', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Stubborn_Friend', label: '嘴硬竹马', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Crisp_Girl', label: '清脆少女', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Pure-hearted_Boy', label: '清澈邻家弟弟', lang: '中文 (普通话)' },
  { value: 'Chinese (Mandarin)_Soft_Girl', label: '柔和少女', lang: '中文 (普通话)' },
  { value: 'Cantonese_ProfessionalHost（F)', label: '专业女主持', lang: '中文 (粤语)' },
  { value: 'Cantonese_GentleLady', label: '温柔女声', lang: '中文 (粤语)' },
  { value: 'Cantonese_ProfessionalHost（M)', label: '专业男主持', lang: '中文 (粤语)' },
  { value: 'Cantonese_PlayfulMan', label: '活泼男声', lang: '中文 (粤语)' },
  { value: 'Cantonese_CuteGirl', label: '可爱女孩', lang: '中文 (粤语)' },
  { value: 'Cantonese_KindWoman', label: '善良女声', lang: '中文 (粤语)' },
  { value: 'Santa_Claus ', label: 'Santa Claus', lang: '英文' },
  { value: 'Grinch', label: 'Grinch', lang: '英文' },
  { value: 'Rudolph', label: 'Rudolph', lang: '英文' },
  { value: 'Arnold', label: 'Arnold', lang: '英文' },
  { value: 'Charming_Santa', label: 'Charming Santa', lang: '英文' },
  { value: 'Charming_Lady', label: 'Charming Lady', lang: '英文' },
  { value: 'Sweet_Girl', label: 'Sweet Girl', lang: '英文' },
  { value: 'Cute_Elf', label: 'Cute Elf', lang: '英文' },
  { value: 'Attractive_Girl', label: 'Attractive Girl', lang: '英文' },
  { value: 'Serene_Woman', label: 'Serene Woman', lang: '英文' },
  { value: 'English_Trustworthy_Man', label: 'Trustworthy Man', lang: '英文' },
  { value: 'English_Graceful_Lady', label: 'Graceful Lady', lang: '英文' },
  { value: 'English_Aussie_Bloke', label: 'Aussie Bloke', lang: '英文' },
  { value: 'English_Whispering_girl', label: 'Whispering girl', lang: '英文' },
  { value: 'English_Diligent_Man', label: 'Diligent Man', lang: '英文' },
  { value: 'English_Gentle-voiced_man', label: 'Gentle-voiced man', lang: '英文' },
  { value: 'Japanese_IntellectualSenior', label: 'Intellectual Senior', lang: '日文' },
  { value: 'Japanese_DecisivePrincess', label: 'Decisive Princess', lang: '日文' },
  { value: 'Japanese_LoyalKnight', label: 'Loyal Knight', lang: '日文' },
  { value: 'Japanese_DominantMan', label: 'Dominant Man', lang: '日文' },
  { value: 'Japanese_SeriousCommander', label: 'Serious Commander', lang: '日文' },
  { value: 'Japanese_ColdQueen', label: 'Cold Queen', lang: '日文' },
  { value: 'Japanese_DependableWoman', label: 'Dependable Woman', lang: '日文' },
  { value: 'Japanese_GentleButler', label: 'Gentle Butler', lang: '日文' },
  { value: 'Japanese_KindLady', label: 'Kind Lady', lang: '日文' },
  { value: 'Japanese_CalmLady', label: 'Calm Lady', lang: '日文' },
  { value: 'Japanese_OptimisticYouth', label: 'Optimistic Youth', lang: '日文' },
  { value: 'Japanese_GenerousIzakayaOwner', label: 'Generous Izakaya Owner', lang: '日文' },
  { value: 'Japanese_SportyStudent', label: 'Sporty Student', lang: '日文' },
  { value: 'Japanese_InnocentBoy', label: 'Innocent Boy', lang: '日文' },
  { value: 'Japanese_GracefulMaiden', label: 'Graceful Maiden', lang: '日文' },
  { value: 'Korean_SweetGirl', label: 'Sweet Girl', lang: '韩文' },
  { value: 'Korean_CheerfulBoyfriend', label: 'Cheerful Boyfriend', lang: '韩文' },
  { value: 'Korean_EnchantingSister', label: 'Enchanting Sister', lang: '韩文' },
  { value: 'Korean_ShyGirl', label: 'Shy Girl', lang: '韩文' },
  { value: 'Korean_ReliableSister', label: 'Reliable Sister', lang: '韩文' },
  { value: 'Korean_StrictBoss', label: 'Strict Boss', lang: '韩文' },
  { value: 'Korean_SassyGirl', label: 'Sassy Girl', lang: '韩文' },
  { value: 'Korean_ChildhoodFriendGirl', label: 'Childhood Friend Girl', lang: '韩文' },
  { value: 'Korean_PlayboyCharmer', label: 'Playboy Charmer', lang: '韩文' },
  { value: 'Korean_ElegantPrincess', label: 'Elegant Princess', lang: '韩文' },
  { value: 'Korean_BraveFemaleWarrior', label: 'Brave Female Warrior', lang: '韩文' },
  { value: 'Korean_BraveYouth', label: 'Brave Youth', lang: '韩文' },
  { value: 'Korean_CalmLady', label: 'Calm Lady', lang: '韩文' },
  { value: 'Korean_EnthusiasticTeen', label: 'Enthusiastic Teen', lang: '韩文' },
  { value: 'Korean_SoothingLady', label: 'Soothing Lady', lang: '韩文' },
  { value: 'Korean_IntellectualSenior', label: 'Intellectual Senior', lang: '韩文' },
  { value: 'Korean_LonelyWarrior', label: 'Lonely Warrior', lang: '韩文' },
  { value: 'Korean_MatureLady', label: 'Mature Lady', lang: '韩文' },
  { value: 'Korean_InnocentBoy', label: 'Innocent Boy', lang: '韩文' },
  { value: 'Korean_CharmingSister', label: 'Charming Sister', lang: '韩文' },
  { value: 'Korean_AthleticStudent', label: 'Athletic Student', lang: '韩文' },
  { value: 'Korean_BraveAdventurer', label: 'Brave Adventurer', lang: '韩文' },
  { value: 'Korean_CalmGentleman', label: 'Calm Gentleman', lang: '韩文' },
  { value: 'Korean_WiseElf', label: 'Wise Elf', lang: '韩文' },
  { value: 'Korean_CheerfulCoolJunior', label: 'Cheerful Cool Junior', lang: '韩文' },
  { value: 'Korean_DecisiveQueen', label: 'Decisive Queen', lang: '韩文' },
  { value: 'Korean_ColdYoungMan', label: 'Cold Young Man', lang: '韩文' },
  { value: 'Korean_MysteriousGirl', label: 'Mysterious Girl', lang: '韩文' },
  { value: 'Korean_QuirkyGirl', label: 'Quirky Girl', lang: '韩文' },
  { value: 'Korean_ConsiderateSenior', label: 'Considerate Senior', lang: '韩文' },
  { value: 'Korean_CheerfulLittleSister', label: 'Cheerful Little Sister', lang: '韩文' },
  { value: 'Korean_DominantMan', label: 'Dominant Man', lang: '韩文' },
  { value: 'Korean_AirheadedGirl', label: 'Airheaded Girl', lang: '韩文' },
  { value: 'Korean_ReliableYouth', label: 'Reliable Youth', lang: '韩文' },
  { value: 'Korean_FriendlyBigSister', label: 'Friendly Big Sister', lang: '韩文' },
  { value: 'Korean_GentleBoss', label: 'Gentle Boss', lang: '韩文' },
  { value: 'Korean_ColdGirl', label: 'Cold Girl', lang: '韩文' },
  { value: 'Korean_HaughtyLady', label: 'Haughty Lady', lang: '韩文' },
  { value: 'Korean_CharmingElderSister', label: 'Charming Elder Sister', lang: '韩文' },
  { value: 'Korean_IntellectualMan', label: 'Intellectual Man', lang: '韩文' },
  { value: 'Korean_CaringWoman', label: 'Caring Woman', lang: '韩文' },
  { value: 'Korean_WiseTeacher', label: 'Wise Teacher', lang: '韩文' },
  { value: 'Korean_ConfidentBoss', label: 'Confident Boss', lang: '韩文' },
  { value: 'Korean_AthleticGirl', label: 'Athletic Girl', lang: '韩文' },
  { value: 'Korean_PossessiveMan', label: 'Possessive Man', lang: '韩文' },
  { value: 'Korean_GentleWoman', label: 'Gentle Woman', lang: '韩文' },
  { value: 'Korean_CockyGuy', label: 'Cocky Guy', lang: '韩文' },
  { value: 'Korean_ThoughtfulWoman', label: 'Thoughtful Woman', lang: '韩文' },
  { value: 'Korean_OptimisticYouth', label: 'Optimistic Youth', lang: '韩文' },
  { value: 'Spanish_SereneWoman', label: 'Serene Woman', lang: '西班牙文' },
  { value: 'Spanish_MaturePartner', label: 'Mature Partner', lang: '西班牙文' },
  { value: 'Spanish_CaptivatingStoryteller', label: 'Captivating Storyteller', lang: '西班牙文' },
  { value: 'Spanish_Narrator', label: 'Narrator', lang: '西班牙文' },
  { value: 'Spanish_WiseScholar', label: 'Wise Scholar', lang: '西班牙文' },
  { value: 'Spanish_Kind-heartedGirl', label: 'Kind-hearted Girl', lang: '西班牙文' },
  { value: 'Spanish_DeterminedManager', label: 'Determined Manager', lang: '西班牙文' },
  { value: 'Spanish_BossyLeader', label: 'Bossy Leader', lang: '西班牙文' },
  { value: 'Spanish_ReservedYoungMan', label: 'Reserved Young Man', lang: '西班牙文' },
  { value: 'Spanish_ConfidentWoman', label: 'Confident Woman', lang: '西班牙文' },
  { value: 'Spanish_ThoughtfulMan', label: 'Thoughtful Man', lang: '西班牙文' },
  { value: 'Spanish_Strong-WilledBoy', label: 'Strong-willed Boy', lang: '西班牙文' },
  { value: 'Spanish_SophisticatedLady', label: 'Sophisticated Lady', lang: '西班牙文' },
  { value: 'Spanish_RationalMan', label: 'Rational Man', lang: '西班牙文' },
  { value: 'Spanish_AnimeCharacter', label: 'Anime Character', lang: '西班牙文' },
  { value: 'Spanish_Deep-tonedMan', label: 'Deep-toned Man', lang: '西班牙文' },
  { value: 'Spanish_Fussyhostess', label: 'Fussy hostess', lang: '西班牙文' },
  { value: 'Spanish_SincereTeen', label: 'Sincere Teen', lang: '西班牙文' },
  { value: 'Spanish_FrankLady', label: 'Frank Lady', lang: '西班牙文' },
  { value: 'Spanish_Comedian', label: 'Comedian', lang: '西班牙文' },
  { value: 'Spanish_Debator', label: 'Debator', lang: '西班牙文' },
  { value: 'Spanish_ToughBoss', label: 'Tough Boss', lang: '西班牙文' },
  { value: 'Spanish_Wiselady', label: 'Wise Lady', lang: '西班牙文' },
  { value: 'Spanish_Steadymentor', label: 'Steady Mentor', lang: '西班牙文' },
  { value: 'Spanish_Jovialman', label: 'Jovial Man', lang: '西班牙文' },
  { value: 'Spanish_SantaClaus', label: 'Santa Claus', lang: '西班牙文' },
  { value: 'Spanish_Rudolph', label: 'Rudolph', lang: '西班牙文' },
  { value: 'Spanish_Intonategirl', label: 'Intonate Girl', lang: '西班牙文' },
  { value: 'Spanish_Arnold', label: 'Arnold', lang: '西班牙文' },
  { value: 'Spanish_Ghost', label: 'Ghost', lang: '西班牙文' },
  { value: 'Spanish_HumorousElder', label: 'Humorous Elder', lang: '西班牙文' },
  { value: 'Spanish_EnergeticBoy', label: 'Energetic Boy', lang: '西班牙文' },
  { value: 'Spanish_WhimsicalGirl', label: 'Whimsical Girl', lang: '西班牙文' },
  { value: 'Spanish_StrictBoss', label: 'Strict Boss', lang: '西班牙文' },
  { value: 'Spanish_ReliableMan', label: 'Reliable Man', lang: '西班牙文' },
  { value: 'Spanish_SereneElder', label: 'Serene Elder', lang: '西班牙文' },
  { value: 'Spanish_AngryMan', label: 'Angry Man', lang: '西班牙文' },
  { value: 'Spanish_AssertiveQueen', label: 'Assertive Queen', lang: '西班牙文' },
  { value: 'Spanish_CaringGirlfriend', label: 'Caring Girlfriend', lang: '西班牙文' },
  { value: 'Spanish_PowerfulSoldier', label: 'Powerful Soldier', lang: '西班牙文' },
  { value: 'Spanish_PassionateWarrior', label: 'Passionate Warrior', lang: '西班牙文' },
  { value: 'Spanish_ChattyGirl', label: 'Chatty Girl', lang: '西班牙文' },
  { value: 'Spanish_RomanticHusband', label: 'Romantic Husband', lang: '西班牙文' },
  { value: 'Spanish_CompellingGirl', label: 'Compelling Girl', lang: '西班牙文' },
  { value: 'Spanish_PowerfulVeteran', label: 'Powerful Veteran', lang: '西班牙文' },
  { value: 'Spanish_SensibleManager', label: 'Sensible Manager', lang: '西班牙文' },
  { value: 'Spanish_ThoughtfulLady', label: 'Thoughtful Lady', lang: '西班牙文' },
  { value: 'Portuguese_SentimentalLady', label: 'Sentimental Lady', lang: '葡萄牙文' },
  { value: 'Portuguese_BossyLeader', label: 'Bossy Leader', lang: '葡萄牙文' },
  { value: 'Portuguese_Wiselady', label: 'Wise lady', lang: '葡萄牙文' },
  { value: 'Portuguese_Strong-WilledBoy', label: 'Strong-willed Boy', lang: '葡萄牙文' },
  { value: 'Portuguese_Deep-VoicedGentleman', label: 'Deep-voiced Gentleman', lang: '葡萄牙文' },
  { value: 'Portuguese_UpsetGirl', label: 'Upset Girl', lang: '葡萄牙文' },
  { value: 'Portuguese_PassionateWarrior', label: 'Passionate Warrior', lang: '葡萄牙文' },
  { value: 'Portuguese_AnimeCharacter', label: 'Anime Character', lang: '葡萄牙文' },
  { value: 'Portuguese_ConfidentWoman', label: 'Confident Woman', lang: '葡萄牙文' },
  { value: 'Portuguese_AngryMan', label: 'Angry Man', lang: '葡萄牙文' },
  { value: 'Portuguese_CaptivatingStoryteller', label: 'Captivating Storyteller', lang: '葡萄牙文' },
  { value: 'Portuguese_Godfather', label: 'Godfather', lang: '葡萄牙文' },
  { value: 'Portuguese_ReservedYoungMan', label: 'Reserved Young Man', lang: '葡萄牙文' },
  { value: 'Portuguese_SmartYoungGirl', label: 'Smart Young Girl', lang: '葡萄牙文' },
  { value: 'Portuguese_Kind-heartedGirl', label: 'Kind-hearted Girl', lang: '葡萄牙文' },
  { value: 'Portuguese_Pompouslady', label: 'Pompous lady', lang: '葡萄牙文' },
  { value: 'Portuguese_Grinch', label: 'Grinch', lang: '葡萄牙文' },
  { value: 'Portuguese_Debator', label: 'Debator', lang: '葡萄牙文' },
  { value: 'Portuguese_SweetGirl', label: 'Sweet Girl', lang: '葡萄牙文' },
  { value: 'Portuguese_AttractiveGirl', label: 'Attractive Girl', lang: '葡萄牙文' },
  { value: 'Portuguese_ThoughtfulMan', label: 'Thoughtful Man', lang: '葡萄牙文' },
  { value: 'Portuguese_PlayfulGirl', label: 'Playful Girl', lang: '葡萄牙文' },
  { value: 'Portuguese_GorgeousLady', label: 'Gorgeous Lady', lang: '葡萄牙文' },
  { value: 'Portuguese_LovelyLady', label: 'Lovely Lady', lang: '葡萄牙文' },
  { value: 'Portuguese_SereneWoman', label: 'Serene Woman', lang: '葡萄牙文' },
  { value: 'Portuguese_SadTeen', label: 'Sad Teen', lang: '葡萄牙文' },
  { value: 'Portuguese_MaturePartner', label: 'Mature Partner', lang: '葡萄牙文' },
  { value: 'Portuguese_Comedian', label: 'Comedian', lang: '葡萄牙文' },
  { value: 'Portuguese_NaughtySchoolgirl', label: 'Naughty Schoolgirl', lang: '葡萄牙文' },
  { value: 'Portuguese_Narrator', label: 'Narrator', lang: '葡萄牙文' },
  { value: 'Portuguese_ToughBoss', label: 'Tough Boss', lang: '葡萄牙文' },
  { value: 'Portuguese_Fussyhostess', label: 'Fussy hostess', lang: '葡萄牙文' },
  { value: 'Portuguese_Dramatist', label: 'Dramatist', lang: '葡萄牙文' },
  { value: 'Portuguese_Steadymentor', label: 'Steady Mentor', lang: '葡萄牙文' },
  { value: 'Portuguese_Jovialman', label: 'Jovial Man', lang: '葡萄牙文' },
  { value: 'Portuguese_CharmingQueen', label: 'Charming Queen', lang: '葡萄牙文' },
  { value: 'Portuguese_SantaClaus', label: 'Santa Claus', lang: '葡萄牙文' },
  { value: 'Portuguese_Rudolph', label: 'Rudolph', lang: '葡萄牙文' },
  { value: 'Portuguese_Arnold', label: 'Arnold', lang: '葡萄牙文' },
  { value: 'Portuguese_CharmingSanta', label: 'Charming Santa', lang: '葡萄牙文' },
  { value: 'Portuguese_CharmingLady', label: 'Charming Lady', lang: '葡萄牙文' },
  { value: 'Portuguese_Ghost', label: 'Ghost', lang: '葡萄牙文' },
  { value: 'Portuguese_HumorousElder', label: 'Humorous Elder', lang: '葡萄牙文' },
  { value: 'Portuguese_CalmLeader', label: 'Calm Leader', lang: '葡萄牙文' },
  { value: 'Portuguese_GentleTeacher', label: 'Gentle Teacher', lang: '葡萄牙文' },
  { value: 'Portuguese_EnergeticBoy', label: 'Energetic Boy', lang: '葡萄牙文' },
  { value: 'Portuguese_ReliableMan', label: 'Reliable Man', lang: '葡萄牙文' },
  { value: 'Portuguese_SereneElder', label: 'Serene Elder', lang: '葡萄牙文' },
  { value: 'Portuguese_GrimReaper', label: 'Grim Reaper', lang: '葡萄牙文' },
  { value: 'Portuguese_AssertiveQueen', label: 'Assertive Queen', lang: '葡萄牙文' },
  { value: 'Portuguese_WhimsicalGirl', label: 'Whimsical Girl', lang: '葡萄牙文' },
  { value: 'Portuguese_StressedLady', label: 'Stressed Lady', lang: '葡萄牙文' },
  { value: 'Portuguese_FriendlyNeighbor', label: 'Friendly Neighbor', lang: '葡萄牙文' },
  { value: 'Portuguese_CaringGirlfriend', label: 'Caring Girlfriend', lang: '葡萄牙文' },
  { value: 'Portuguese_PowerfulSoldier', label: 'Powerful Soldier', lang: '葡萄牙文' },
  { value: 'Portuguese_FascinatingBoy', label: 'Fascinating Boy', lang: '葡萄牙文' },
  { value: 'Portuguese_RomanticHusband', label: 'Romantic Husband', lang: '葡萄牙文' },
  { value: 'Portuguese_StrictBoss', label: 'Strict Boss', lang: '葡萄牙文' },
  { value: 'Portuguese_InspiringLady', label: 'Inspiring Lady', lang: '葡萄牙文' },
  { value: 'Portuguese_PlayfulSpirit', label: 'Playful Spirit', lang: '葡萄牙文' },
  { value: 'Portuguese_ElegantGirl', label: 'Elegant Girl', lang: '葡萄牙文' },
  { value: 'Portuguese_CompellingGirl', label: 'Compelling Girl', lang: '葡萄牙文' },
  { value: 'Portuguese_PowerfulVeteran', label: 'Powerful Veteran', lang: '葡萄牙文' },
  { value: 'Portuguese_SensibleManager', label: 'Sensible Manager', lang: '葡萄牙文' },
  { value: 'Portuguese_ThoughtfulLady', label: 'Thoughtful Lady', lang: '葡萄牙文' },
  { value: 'Portuguese_TheatricalActor', label: 'Theatrical Actor', lang: '葡萄牙文' },
  { value: 'Portuguese_FragileBoy', label: 'Fragile Boy', lang: '葡萄牙文' },
  { value: 'Portuguese_ChattyGirl', label: 'Chatty Girl', lang: '葡萄牙文' },
  { value: 'Portuguese_Conscientiousinstructor', label: 'Conscientious Instructor', lang: '葡萄牙文' },
  { value: 'Portuguese_RationalMan', label: 'Rational Man', lang: '葡萄牙文' },
  { value: 'Portuguese_WiseScholar', label: 'Wise Scholar', lang: '葡萄牙文' },
  { value: 'Portuguese_FrankLady', label: 'Frank Lady', lang: '葡萄牙文' },
  { value: 'Portuguese_DeterminedManager', label: 'Determined Manager', lang: '葡萄牙文' },
  { value: 'French_Male_Speech_New', label: 'Level-Headed Man', lang: '法文' },
  { value: 'French_Female_News Anchor', label: 'Patient Female Presenter', lang: '法文' },
  { value: 'French_CasualMan', label: 'Casual Man', lang: '法文' },
  { value: 'French_MovieLeadFemale', label: 'Movie Lead Female', lang: '法文' },
  { value: 'French_FemaleAnchor', label: 'Female Anchor', lang: '法文' },
  { value: 'French_MaleNarrator', label: 'Male Narrator', lang: '法文' },
  { value: 'Indonesian_SweetGirl', label: 'Sweet Girl', lang: '印尼文' },
  { value: 'Indonesian_ReservedYoungMan', label: 'Reserved Young Man', lang: '印尼文' },
  { value: 'Indonesian_CharmingGirl', label: 'Charming Girl', lang: '印尼文' },
  { value: 'Indonesian_CalmWoman', label: 'Calm Woman', lang: '印尼文' },
  { value: 'Indonesian_ConfidentWoman', label: 'Confident Woman', lang: '印尼文' },
  { value: 'Indonesian_CaringMan', label: 'Caring Man', lang: '印尼文' },
  { value: 'Indonesian_BossyLeader', label: 'Bossy Leader', lang: '印尼文' },
  { value: 'Indonesian_DeterminedBoy', label: 'Determined Boy', lang: '印尼文' },
  { value: 'Indonesian_GentleGirl', label: 'Gentle Girl', lang: '印尼文' },
  { value: 'German_FriendlyMan', label: 'Friendly Man', lang: '德文' },
  { value: 'German_SweetLady', label: 'Sweet Lady', lang: '德文' },
  { value: 'German_PlayfulMan', label: 'Playful Man', lang: '德文' },
  { value: 'Russian_HandsomeChildhoodFriend', label: 'Handsome Childhood Friend', lang: '俄文' },
  { value: 'Russian_BrightHeroine', label: 'Bright Queen', lang: '俄文' },
  { value: 'Russian_AmbitiousWoman', label: 'Ambitious Woman', lang: '俄文' },
  { value: 'Russian_ReliableMan', label: 'Reliable Man', lang: '俄文' },
  { value: 'Russian_CrazyQueen', label: 'Crazy Girl', lang: '俄文' },
  { value: 'Russian_PessimisticGirl', label: 'Pessimistic Girl', lang: '俄文' },
  { value: 'Russian_AttractiveGuy', label: 'Attractive Guy', lang: '俄文' },
  { value: 'Russian_Bad-temperedBoy', label: 'Bad-tempered Boy', lang: '俄文' },
  { value: 'Italian_BraveHeroine', label: 'Brave Heroine', lang: '意大利文' },
  { value: 'Italian_Narrator', label: 'Narrator', lang: '意大利文' },
  { value: 'Italian_WanderingSorcerer', label: 'Wandering Sorcerer', lang: '意大利文' },
  { value: 'Italian_DiligentLeader', label: 'Diligent Leader', lang: '意大利文' },
  { value: 'Arabic_CalmWoman', label: 'Calm Woman', lang: '阿拉伯文' },
  { value: 'Arabic_FriendlyGuy', label: 'Friendly Guy', lang: '阿拉伯文' },
  { value: 'Turkish_CalmWoman', label: 'Calm Woman', lang: '土耳其文' },
  { value: 'Turkish_Trustworthyman', label: 'Trustworthy man', lang: '土耳其文' },
  { value: 'Ukrainian_CalmWoman', label: 'Calm Woman', lang: '乌克兰文' },
  { value: 'Ukrainian_WiseScholar', label: 'Wise Scholar', lang: '乌克兰文' },
  { value: 'Dutch_kindhearted_girl', label: 'Kind-hearted girl', lang: '荷兰文' },
  { value: 'Dutch_bossy_leader', label: 'Bossy leader', lang: '荷兰文' },
  { value: 'Vietnamese_kindhearted_girl', label: 'Kind-hearted girl', lang: '越南文' },
  { value: 'Thai_male_1_sample8', label: 'Serene Man', lang: '泰文' },
  { value: 'Thai_male_2_sample2', label: 'Friendly Man', lang: '泰文' },
  { value: 'Thai_female_1_sample1', label: 'Confident Woman', lang: '泰文' },
  { value: 'Thai_female_2_sample2', label: 'Energetic Woman', lang: '泰文' },
  { value: 'Polish_male_1_sample4', label: 'Male Narrator', lang: '波兰文' },
  { value: 'Polish_male_2_sample3', label: 'Male Anchor', lang: '波兰文' },
  { value: 'Polish_female_1_sample1', label: 'Calm Woman', lang: '波兰文' },
  { value: 'Polish_female_2_sample3', label: 'Casual Woman', lang: '波兰文' },
  { value: 'Romanian_male_1_sample2', label: 'Reliable Man', lang: '罗马尼亚文' },
  { value: 'Romanian_male_2_sample1', label: 'Energetic Youth', lang: '罗马尼亚文' },
  { value: 'Romanian_female_1_sample4', label: 'Optimistic Youth', lang: '罗马尼亚文' },
  { value: 'Romanian_female_2_sample1', label: 'Gentle Woman', lang: '罗马尼亚文' },
  { value: 'greek_male_1a_v1', label: 'Thoughtful Mentor', lang: '希腊文' },
  { value: 'Greek_female_1_sample1', label: 'Gentle Lady', lang: '希腊文' },
  { value: 'Greek_female_2_sample3', label: 'Girl Next Door', lang: '希腊文' },
  { value: 'czech_male_1_v1', label: 'Assured Presenter', lang: '捷克文' },
  { value: 'czech_female_5_v7', label: 'Steadfast Narrator', lang: '捷克文' },
  { value: 'czech_female_2_v2', label: 'Elegant Lady', lang: '捷克文' },
  { value: 'finnish_male_3_v1', label: 'Upbeat Man', lang: '芬兰文' },
  { value: 'finnish_male_1_v2', label: 'Friendly Boy', lang: '芬兰文' },
  { value: 'finnish_female_4_v1', label: 'Assetive Woman', lang: '芬兰文' },
  { value: 'hindi_male_1_v2', label: 'Trustworthy Advisor', lang: '印地文' },
  { value: 'hindi_female_2_v1', label: 'Tranquil Woman', lang: '印地文' },
  { value: 'hindi_female_1_v2', label: 'News Anchor', lang: '印地文' }
] as const satisfies readonly MiniMaxSystemVoice[];

export const MINIMAX_SYSTEM_VOICE_GROUPS = MINIMAX_SYSTEM_VOICES.reduce<MiniMaxSystemVoiceGroup[]>((groups, voice) => {
  const currentGroup = groups[groups.length - 1];
  if (currentGroup?.lang === voice.lang) {
    currentGroup.voices.push(voice);
  } else {
    groups.push({ lang: voice.lang, voices: [voice] });
  }
  return groups;
}, []);
