import fs from 'node:fs/promises';

import type { ToolDefinition } from '@mariozechner/pi-coding-agent';
import { Type, type Static } from '@sinclair/typebox';

import type { ChatCardType } from '../../../types';
import { resolveGuardedToolExecution } from '../skills';
import type { PiSessionToolContext } from '../tool-context';
import { createJsonToolResult } from './result';

const resourceTypeParameter = Type.Union([
  Type.Literal('image'),
  Type.Literal('video'),
  Type.Literal('audio'),
  Type.Literal('recording'),
  Type.Literal('subtitle'),
  Type.Literal('text'),
  Type.Literal('link'),
  Type.Literal('file'),
  Type.Literal('document'),
  Type.Literal('rss'),
  Type.Literal('translation'),
  Type.Literal('summary'),
  Type.Literal('mindmap'),
  Type.Literal('note'),
  Type.Literal('screenshot'),
  Type.Literal('other')
]);

const stringListParameter = Type.Union([Type.Array(Type.String()), Type.String()]);
const metadataParameter = Type.Union([Type.Object({}, { additionalProperties: true }), Type.String()]);

const resourceCreateParameters = Type.Object({
  filePath: Type.Optional(Type.String({ description: 'Local file path to import into the resource library.' })),
  url: Type.Optional(Type.String({ description: 'Optional source URL. Without filePath/contentText this creates a link resource.' })),
  contentText: Type.Optional(Type.String({ description: 'Text content for creating a text resource.' })),
  title: Type.Optional(Type.String({ description: 'Resource title.' })),
  description: Type.Optional(Type.String({ description: 'Resource description.' })),
  type: Type.Optional(resourceTypeParameter),
  mimeType: Type.Optional(Type.String({ description: 'Optional MIME type.' })),
  sizeBytes: Type.Optional(Type.Number({ description: 'Optional file size in bytes.' })),
  durationMs: Type.Optional(Type.Number({ description: 'Optional media duration in milliseconds.' })),
  sourceName: Type.Optional(Type.String({ description: 'Optional source/provider name.' })),
  domain: Type.Optional(Type.String({ description: 'Optional source domain.' })),
  tags: Type.Optional(stringListParameter),
  categories: Type.Optional(stringListParameter),
  metadata: Type.Optional(metadataParameter),
  mediaKind: Type.Optional(
    Type.Union([Type.Literal('music'), Type.Literal('speech'), Type.Literal('recording'), Type.Literal('sound-effect'), Type.Literal('unknown')], {
      description: 'Audio/media semantic kind. Use music for generated songs/background music so players can distinguish it from speech/recordings.'
    })
  ),
  aiGenerated: Type.Optional(Type.Boolean({ description: 'Whether this resource was generated by AI.' })),
  workspaceId: Type.Optional(Type.String({ description: 'Target workspace ID. Defaults to current conversation/default workspace.' })),
  folderId: Type.Optional(Type.String({ description: 'Target folder ID. If omitted, addResource chooses the default/daily folder.' })),
  parentResourceId: Type.Optional(Type.String({ description: 'Optional parent resource ID.' })),
  pushCard: Type.Optional(Type.Boolean({ description: 'Whether to push a resource card into chat. Defaults to true.' }))
});

type ResourceCreateInput = Static<typeof resourceCreateParameters>;

type ResourceCreator = (resource: Record<string, any>) => Promise<{ data?: Record<string, any> | null; error?: string; success: boolean }>;

export interface ResourceCreateToolBindings {
  resourceCreator?: ResourceCreator;
}

async function getDefaultResourceCreator(): Promise<ResourceCreator> {
  const { addResource } = await import('../../../../common/db');
  return async (resource) => addResource({ resource } as any) as any;
}

function trimString(value: unknown): string | undefined {
  const text = typeof value === 'string' ? value.trim() : '';
  return text || undefined;
}

function normalizeStringList(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value.map((item) => String(item || '').trim()).filter(Boolean);
  }

  if (typeof value !== 'string' || !value.trim()) {
    return [];
  }

  const text = value.trim();
  try {
    const parsed = JSON.parse(text);
    if (Array.isArray(parsed)) {
      return normalizeStringList(parsed);
    }
  } catch {
    // fall through to comma splitting
  }

  return text
    .split(/[,\n，、;；]+/)
    .map((item) => item.trim())
    .filter(Boolean);
}

function dedupe(values: string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];

  for (const value of values) {
    const key = value.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    result.push(value);
  }

  return result;
}

function normalizeMetadata(value: unknown): Record<string, any> {
  if (!value) return {};
  if (typeof value === 'string') {
    try {
      const parsed = JSON.parse(value);
      return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? { ...parsed } : {};
    } catch {
      return { note: value };
    }
  }

  return typeof value === 'object' && !Array.isArray(value) ? { ...(value as Record<string, any>) } : {};
}

async function resolveFileSize(filePath?: string, fallback?: number): Promise<number | undefined> {
  if (typeof fallback === 'number' && Number.isFinite(fallback) && fallback >= 0) {
    return fallback;
  }

  if (!filePath) return undefined;

  const stat = await fs.stat(filePath);
  if (!stat.isFile()) {
    throw new Error(`资源文件不是普通文件: ${filePath}`);
  }

  return stat.size;
}

async function resolveWorkspaceId(toolContext: PiSessionToolContext, explicitWorkspaceId?: string, folderId?: string): Promise<string | undefined> {
  const workspaceId = trimString(explicitWorkspaceId) || trimString(toolContext.resolved.request.extras?.workspaceId);
  if (workspaceId) {
    return workspaceId;
  }

  if (folderId) {
    const { FoldersRepo } = await import('../../../../common/db');
    const folder = await FoldersRepo.getById(folderId);
    if (folder?.workspaceId) {
      return folder.workspaceId;
    }
  }

  return undefined;
}

function resolveFolderId(toolContext: PiSessionToolContext, explicitFolderId?: string): string | undefined {
  return trimString(explicitFolderId) || trimString(toolContext.resolved.request.extras?.folderId);
}

export async function createResourceRecord(
  toolContext: PiSessionToolContext,
  input: Omit<ResourceCreateInput, 'pushCard'>,
  bindings: ResourceCreateToolBindings = {}
): Promise<{ resource: Record<string, any>; resourceId: string }> {
  const filePath = trimString(input.filePath);
  const url = trimString(input.url);
  const contentText = trimString(input.contentText);

  if (!filePath && !url && !contentText) {
    throw new Error('创建资源需要提供 filePath、url 或 contentText。');
  }

  const metadata = normalizeMetadata(input.metadata);
  if (input.mediaKind) {
    metadata.mediaKind = input.mediaKind;
    metadata.kind = metadata.kind || input.mediaKind;
  }
  if (input.aiGenerated !== undefined) {
    metadata.aiGenerated = input.aiGenerated;
  }

  const tags = normalizeStringList(input.tags);
  const categories = normalizeStringList(input.categories);
  if (input.mediaKind === 'music') {
    tags.push('music');
    categories.push('music');
  }
  if (input.aiGenerated) {
    tags.push('ai-generated');
    categories.push('ai-generated');
  }

  const resource: Record<string, any> = {
    ...(input.type ? { type: input.type } : {}),
    ...(filePath ? { filePath } : {}),
    ...(url ? { url } : {}),
    ...(contentText ? { contentText } : {}),
    ...(trimString(input.title) ? { title: trimString(input.title) } : {}),
    ...(trimString(input.description) ? { description: trimString(input.description) } : {}),
    ...(trimString(input.mimeType) ? { mimeType: trimString(input.mimeType) } : {}),
    ...(trimString(input.sourceName) ? { sourceName: trimString(input.sourceName) } : {}),
    ...(trimString(input.domain) ? { domain: trimString(input.domain) } : {}),
    ...(typeof input.durationMs === 'number' && Number.isFinite(input.durationMs) ? { durationMs: input.durationMs } : {}),
    ...(input.parentResourceId ? { parentResourceId: trimString(input.parentResourceId) } : {}),
    ...(Object.keys(metadata).length ? { metadata: JSON.stringify(metadata) } : {}),
    ...(tags.length ? { tags: JSON.stringify(dedupe(tags)) } : {}),
    ...(categories.length ? { categories: JSON.stringify(dedupe(categories)) } : {})
  };

  const folderId = resolveFolderId(toolContext, input.folderId);
  const workspaceId = await resolveWorkspaceId(toolContext, input.workspaceId, folderId);
  if (workspaceId) resource.workspaceId = workspaceId;
  if (folderId) resource.folderId = folderId;

  const sizeBytes = await resolveFileSize(filePath, input.sizeBytes);
  if (sizeBytes !== undefined) {
    resource.sizeBytes = sizeBytes;
  }

  const creator = bindings.resourceCreator || (await getDefaultResourceCreator());
  const result = await creator(resource);
  if (!result?.success || !result.data?.id) {
    throw new Error(result?.error || '资源创建失败');
  }

  return {
    resource: result.data,
    resourceId: String(result.data.id)
  };
}

function toCardType(resourceType?: string): ChatCardType {
  switch (resourceType) {
    case 'audio':
    case 'document':
    case 'file':
    case 'image':
    case 'link':
    case 'video':
      return resourceType;
    default:
      return 'resource';
  }
}

function pushResourceCard(toolContext: PiSessionToolContext, resource: Record<string, any>, text?: string): void {
  toolContext.pushCardToWindows(
    {
      conversationId: toolContext.conversationId,
      resourceId: String(resource.id),
      text,
      type: toCardType(resource.type)
    },
    toolContext.targetWindowId
  );
}

export function createPiResourceCreateTool(toolContext: PiSessionToolContext, bindings: ResourceCreateToolBindings = {}): ToolDefinition<typeof resourceCreateParameters> {
  return {
    name: 'resourceCreateTool',
    label: 'resourceCreateTool',
    description:
      'Create a resource library entry from a local file path, URL, or text content. Use mediaKind="music" for generated music so players/sprites can distinguish music from speech or recordings.',
    parameters: resourceCreateParameters,
    async execute(toolCallId, input) {
      try {
        const guardResolution = await resolveGuardedToolExecution(toolContext, toolCallId, 'resource-create');
        if (guardResolution?.kind === 'blocked' || guardResolution?.kind === 'cancel') {
          return createJsonToolResult(guardResolution.details);
        }

        const result = await createResourceRecord(toolContext, input, bindings);
        if (input.pushCard !== false) {
          pushResourceCard(toolContext, result.resource, input.title ? `已创建资源：${input.title}` : '已创建资源');
        }

        return createJsonToolResult({
          success: true,
          resourceId: result.resourceId,
          resource: result.resource,
          isMusic: result.resource.metadata ? normalizeMetadata(result.resource.metadata).mediaKind === 'music' : input.mediaKind === 'music',
          ...(guardResolution?.warning ? { warning: guardResolution.warning } : {})
        });
      } catch (error: any) {
        return createJsonToolResult({
          success: false,
          error: error?.message || '创建资源失败'
        });
      }
    }
  };
}
