/**
 * Memory System TypeScript 类型定义
 * 定义 Frontmatter、提取输出、检索结果等核心接口。
 */

import type { TokenUsage } from '../types';

// ━━ Memory Note Frontmatter ━━

export interface MemoryNoteEntity {
  name: string;
  type: 'person' | 'product' | 'technology' | 'organization' | 'concept' | 'location' | 'event' | 'other';
  /** 实体关系（可选），用于时序实体知识图谱 */
  relations?: Array<{
    predicate: string; // 如 "works_on", "prefers", "collaborates_with"
    object: string; // 目标实体名
    validFrom?: string; // 开始时间，如 "2026-04"
  }>;
}

export type MemoryNoteContradictionType = 'decision_change' | 'attribution_conflict' | 'factual_conflict';

export interface MemoryNoteContradiction {
  old: string;
  new: string;
  type: MemoryNoteContradictionType;
  detectedAt: number; // 毫秒时间戳
}

export interface MemoryNoteMessageRange {
  conversationId: string;
  seqStart: number;
  seqEnd: number;
}

export interface MemoryNoteTimeRange {
  start: number; // 毫秒时间戳
  end: number;
}

export interface MemoryNoteFrontmatter {
  // 身份
  id: string;
  version: number;

  // 归属
  workspaceId: string;
  date: string; // YYYY-MM-DD
  timeRange?: MemoryNoteTimeRange;

  // 主题与分类
  topics: string[]; // 至少 1 个
  parentTopicId?: string;
  relatedTopicIds?: string[];
  /** 领域命名空间，如 "person:Alice", "project:chobits", "general" */
  domain?: string;

  // 关键词与实体
  keywords: string[]; // 至少 3 个
  aliases?: string[];
  entities?: MemoryNoteEntity[];

  // 摘要
  summary: string;
  contradictions?: MemoryNoteContradiction[];

  // 溯源
  sourceConversationIds: string[];
  sourceMessageRange?: MemoryNoteMessageRange[];

  // 权重与稳定度
  importance: number; // 0.0 ~ 1.0
  stability: number; // 0.0 ~ 1.0

  // 生命周期
  createdAt: number; // 毫秒时间戳
  updatedAt: number;
}

// ━━ Section Index ━━

export interface MemoryNoteSectionIndex {
  noteId: string;
  heading: string; // 标题路径，如 "Key Points"
  headingLevel: number; // 2 | 3
  summary: string; // 段落摘要
  keywords: string[]; // 段落级关键词
  lineStart: number; // 起始行号 (1-based)
  lineEnd: number; // 结束行号 (1-based)
  charCount: number;
}

// ━━ LLM Extraction Output ━━

/** LLM 主题拆分输出 */
export interface TopicCluster {
  topicLabel: string;
  topicSlug: string;
  description: string;
  messageRanges: Array<{
    conversationId: string;
    seqStart: number;
    seqEnd: number;
  }>;
  estimatedImportance: number;
  /** 领域命名空间，如 "person:Alice", "project:chobits", "general" */
  domain?: string;
}

export interface TopicSplitOutput {
  topicClusters: TopicCluster[];
}

/** LLM 结构化提取输出（单个主题） */
export interface MemoryExtractionOutput {
  topicLabel: string;
  topicSlug: string;
  /** Internal canonicalization aliases added after extraction, not generated by the LLM. */
  topicAliases?: string[];
  summary: string;
  importance: number;
  stability: number;
  keywords: string[];
  entities?: MemoryNoteEntity[];
  sections: {
    keyPoints: string;
    openItems?: string;
    /**
     * 长期记忆候选（可选）：
     * 每条必须使用 `- [kind] 内容` 形式，其中 kind ∈
     * ongoing | decision | principle | event | follow_up
     */
    recallCues?: string;
  };
  /**
   * 原始对话关键片段（可选）：
   * 仅在 importance > 0.8 时由 LLM 提取，每条 ≤ 200 字符，最多 3 条。
   * 用于保留用户原话作为日后检索佐证。
   */
  sourceExcerpts?: string[];
}

// ━━ Merge Result ━━

export interface MergedNote {
  action: 'create' | 'update';
  noteId: string;
  frontmatter: MemoryNoteFrontmatter;
  sections: Map<string, string>; // heading → markdown content
  filePath: string; // workspace-relative path
}

// ━━ Write Result ━━

export interface WriteStats {
  notesCreated: number;
  notesUpdated: number;
  topicsCreated: number;
  edgesCreated: number;
  keywordsCreated: number;
}

// ━━ Collect Phase ━━

export interface CollectInput {
  conversationIds: string[];
  /** 增量模式：只取 seq > watermark 的消息 */
  watermarks?: Map<string, number>;
}

export interface CollectedMessage {
  role: 'user' | 'assistant';
  content: string;
  seq: number;
  createdAt: number;
}

export interface CollectedConversation {
  conversationId: string;
  title?: string;
  messages: CollectedMessage[];
}

export interface CollectOutput {
  conversations: CollectedConversation[];
  totalMessageCount: number;
  dateRange: { start: string; end: string };
}

// ━━ Extraction Job ━━

export type MemorySyncJobType = 'daily_extraction' | 'conversation_close' | 'manual_reindex' | 'file_change_reindex' | 'recall_cue_backfill';

export interface ExtractionJobParams {
  jobType: MemorySyncJobType;
  workspaceId: string;
  targetDate?: string;
  targetConversationIds: string[];
  /** 用于 Recall Cues 回填的目标 note 列表 */
  targetNoteIds?: string[];
  /** 用于 Recall Cues 回填的最大处理数量 */
  backfillLimit?: number;
  /** 触发提取时的实际 provider（优先使用，避免读取 stale 的会话记录） */
  providerId?: string;
  /** 触发提取时的实际 provider preset */
  providerPresetId?: string;
}

export interface ExtractionProgress {
  stage: 'collect' | 'split' | 'extract' | 'merge' | 'write';
  current: number;
  total: number;
  currentTopic?: string;
  message?: string;
}

export interface ExtractionResult {
  succeeded: Array<{ topicSlug: string; noteId: string }>;
  failed: Array<{ topicSlug: string; error: string }>;
  stats: WriteStats;
}

// ━━ Extraction Config ━━

export interface MemoryExtractionConfig {
  /** 是否启用自动记忆提取 */
  enabled: boolean;
  /** 触发提取的最少新增消息数 */
  minNewMessages: number; // default: 4
  /** 会话结束触发的最小间隔（毫秒） */
  minTriggerInterval: number; // default: 30 * 60 * 1000
  /** 单次提取的最大 token 预算 */
  maxTokensPerExtraction: number; // default: 20000
  /** 使用的 AI provider 和 model */
  providerId?: string;
  model?: string;
}

export const DEFAULT_EXTRACTION_CONFIG: MemoryExtractionConfig = {
  enabled: true,
  minNewMessages: 4,
  minTriggerInterval: 5 * 60 * 1000,
  maxTokensPerExtraction: 4000
};

// ━━ Agent Loop Complete Payload ━━

export interface AgentLoopToolCallInfo {
  callId: string;
  name: string;
  args?: any;
  result?: any;
}

/**
 * Agent 工具调用循环结束后发出的事件负载。
 * 参考 Claude Code 的 handleStopHooks 机制：
 * 只在模型最终回复（无后续 tool_use）时触发。
 */
export interface AgentLoopCompletePayload {
  conversationId: string;
  /** 本轮 agent 循环中的所有工具调用 */
  toolCalls: AgentLoopToolCallInfo[];
  /** 是否包含工具调用（快捷判断） */
  hasToolCalls: boolean;
  /** 助手最终回复的文本长度（用于判断信息密度） */
  assistantContentLength: number;
  /** 运行时类型 */
  runtime: 'pi' | 'openai' | 'other';
  /** 本轮是否持久化了消息 */
  persisted: boolean;
  /** agent / profile ID */
  agentId?: string;
  /** 本轮实际使用的 provider（用于记忆提取选择模型） */
  providerId?: string;
  /** 本轮实际使用的 provider preset */
  providerPresetId?: string;
}

// ━━ Chat function type for LLM calls ━━

export interface MemoryChatInvocation {
  completedAt: number;
  rawUsage?: unknown;
  startedAt: number;
  status: 'completed' | 'failed' | 'cancelled';
  usage?: TokenUsage;
}

export interface MemoryUsageEvent extends MemoryChatInvocation {
  attemptIndex?: number;
  metadata?: Record<string, unknown>;
  operationKey: string;
  usageStage: 'analyze' | 'extract' | 'merge';
}

export interface MemoryChatFn {
  (prompt: string, signal?: AbortSignal): Promise<string>;
  consumeLastInvocation?: () => MemoryChatInvocation | undefined;
}
