name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: pnpm install

      - name: Download Platform Resources (macOS)
        if: runner.os == 'macOS'
        run: pnpm run download-ffmpeg-darwin-arm64 && pnpm run download-ytdlp-darwin && pnpm run download-7zip-darwin-arm64

      - name: Download Platform Resources (Windows)
        if: runner.os == 'Windows'
        run: pnpm run download-ffmpeg-win32-x64 && pnpm run download-ytdlp-win32 && pnpm run download-7zip-win32-x64

      - name: Download Platform Resources (Linux)
        if: runner.os == 'Linux'
        run: pnpm run download-7zip-linux-x64

      - name: Build Release Files
        run: pnpm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release_on_${{ matrix. os }}
          path: release/
          retention-days: 5