export enum AppEvent {
  // Workspace
  WORKSPACE_CREATED = 'WORKSPACE_CREATED',
  WORKSPACE_UPDATED = 'WORKSPACE_UPDATED',
  WORKSPACE_DELETED = 'WORKSPACE_DELETED',

  // Folder
  FOLDER_CREATED = 'FOLDER_CREATED',
  FOLDER_UPDATED = 'FOLDER_UPDATED',
  FOLDER_DELETED = 'FOLDER_DELETED',
  FOLDER_MOVED = 'FOLDER_MOVED',

  // Resource
  RESOURCE_CREATED = 'RESOURCE_CREATED',
  RESOURCE_UPDATED = 'RESOURCE_UPDATED',
  RESOURCE_DELETED = 'RESOURCE_DELETED',
  RESOURCE_MOVED = 'RESOURCE_MOVED',
  RESOURCE_BATCH_DELETED = 'RESOURCE_BATCH_DELETED',
  RESOURCE_BATCH_MOVED = 'RESOURCE_BATCH_MOVED',

  // Tag
  TAG_CREATED = 'TAG_CREATED',
  TAG_UPDATED = 'TAG_UPDATED',
  TAG_DELETED = 'TAG_DELETED',

  // Sprite
  SPRITE_MESSAGE = 'SPRITE_MESSAGE'
}

export interface AppEventPayload<T = any> {
  type: AppEvent;
  data?: T;
  timestamp: number;
  sourceWindowId?: number; // ID of the window that initiated the change
}

export const APP_EVENT_CHANNEL = 'APP_EVENT_CHANNEL';
